name: "build binaries"

on:
  pull_request:
  push: 
    branches:  ["main", "develop", "feature/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets. GITHUB_TOKEN }}
      
      - uses: cachix/cachix-action@v15
        if: github.event_name == 'push'
        with:
          name:  openmensa-parser-darmstadt
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - uses: cachix/cachix-action@v15
        if: github.event_name == 'pull_request'
        with: 
          name: openmensa-parser-darmstadt

      - name: build cli
        run: nix build .#cli
      
      - name: build server
        run: nix build .#server
